[workspace]

members = [
    "crates/*",
]

exclude = [
    "integration-tests",
]

[profile.release]
strip = true

[patch.crates-io]
# patch for wasm compilation
ext-php-rs = { git = "https://github.com/bbutkovic/ext-php-rs", branch = "wasm-target" }
