[package]
name = "fastly-php-runtime"
version = "0.1.0"
edition = "2021"

publish = false

[dependencies]
bytes = "1.4.0"
fastly = "^0.8.6"
fastly-sys = "0.9.1"
lazy_static = "1.4.0"
php-sys = { path = "../php-sys" }
