name: Runtime
on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.2
      with:
        version: "v0.4.0"

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: >
        sudo apt-get install -y re2c llvm-15 &&
        sudo ln -s $(which wasm-ld-14 || which wasm-ld-13 || which wasm-ld-12 || which wasm-ld-11 || which wasm-ld-10) /usr/bin/wasm-ld &&
        curl -sSLO https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-19/wasi-sdk-19.0-linux.tar.gz &&
        tar xzf wasi-sdk-19.0-linux.tar.gz &&
        mv wasi-sdk-19.0 /opt/wasi-sdk &&
        ln -s /opt/wasi-sdk/lib/clang/15.0.7/lib/wasi/libclang_rt.builtins-wasm32.a /opt/wasi-sdk/lib/clang/15.0.7/lib/wasi/libclang_rt.a &&
        echo "WASI_SDK_PATH=/opt/wasi-sdk" >> $GITHUB_ENV

    - name: Build runtime
      run: make all use_sccache=true WASI_SDK_PATH=$WASI_SDK_PATH numjobs=3

    - name: Upload runtime
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v3
      with:
        name: runtime
        path: |
          runtime.wasm
          fastly-php-runtime.stubs.php

    - name: Run sccache stat for check
      shell: bash
      run: ${SCCACHE_PATH} --show-stats

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: runtime
      - name: Create release
        uses: softprops/action-gh-release@v0.1.15
        with:
          prerelase: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            runtime.wasm
            fastly-php-runtime.stubs.php
