name: Runtime
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies
      run: >
        apt-get install -y re2c &&
        curl -sSLO https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-19/wasi-sdk-19.0-linux.tar.gz &&
        tar xzf wasi-sdk-19.0-linux.tar.gz &&
        mv wasi-sdk-19.0 /opt/wasi-sdk &&
        echo "WASI_SDK_PATH=/opt/wasi-sdk" >> $GITHUB_ENV

    - name: Build runtime
      run: make runtime.wasm WASI_SDK_PATH=$WASI_SDK_PATH numjobs=3